# Generated by Django 4.2.5 on 2023-10-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='status',
            field=models.CharField(choices=[('E', 'Em análise'), ('F', 'Finalizado')], default='E', max_length=2),
        ),
    ]
